### ISSUE TITLE
Blacklist join columns

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/datamart-frontend#1]
when searching with time or string, we suggest calendar and precision as possible join columns. We should black list calendar, precision, variable, variable_name , source_of_fileLabel, data_curatorLabel, geo_precision and any others that you think would be meaningless.

**Comment by ckxz105** [comment]
I just checked, it turns out except calendar, other columns won't be searched as they are defined as CategoricalData columns which we will not search on them. The only problem is `calendar` column is Q node columns which we will always search on it. 

So it seems the only way to not display it is add some constrains like if we find all `same content` in on columns, ignore that, even Q node column. If you agree with this method, I will fix in this way.

**Comment by szeke** [comment]
I think for the calendar you can just blacklist if most of the values are `= Q12138` which is Gregorian calendar. Longer term we may want to  do something more sophisticated such as instances of some class, e.g., :
```
# Instances of Calendar
SELECT ?item ?itemLabel 
WHERE 
{
  ?item wdt:P31/wdt:P279* wd:Q12132.
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
```

**Comment by ckxz105** [comment]
I have fixed in the blacklist method. Now the system will run the query you provided (which is upgradable in the future). Then get all the Q nodes returned from that query and treat these Q nodes as blacklist. 
If we then search on those Q nodes, we will remove them from search list. If the list become empty after removing, we will remove this search result.
This fix should be pushed to datamachine later today.
